[package]
name = "rustcolor"
version = "0.1.0"
authors = ["Júlio César de Brito Gardona <jcbritobr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
